"""Executive Decision Agent — a CrewAI crew invoked inside a LangGraph node.

Per docs/04_agent_design.md 2.10: four roles (Operations Analyst, Sustainability
Auditor, Risk Officer, Chief of Staff) synthesise the other nine agents' outputs
into a ranked action plan, a risk register, and explicit conflict resolution —
patient safety before regulatory compliance before cost before sustainability.

Unlike every other agent in this codebase, this one has **no partial LLM
degrade** — the synthesis and conflict-resolution reasoning the spec describes
*is* the LLM's job here, not a rationale layered on top of a number a rule engine
already computed. So ``analyse()`` raises immediately with no Gemini key
configured, and ``fallback()`` is a genuinely different, deterministic
mechanism: rank the signals already sitting in shared state by a fixed severity
order and template the result, rather than attempt any crew reasoning at all.
That fallback is what runs in this project's default configuration (no API key
set) and is exercised directly by the test suite; the CrewAI path is exercised
whenever ``GOOGLE_API_KEY`` is configured.
"""

from __future__ import annotations

import json
import os
from typing import Any

from app.agents.base import AgentResult, BaseAgent
from app.agents.llm import llm_ready
from app.agents.state import HealMatrixState, messages_for, result_of
from app.core.config import settings
from app.core.constants import AgentName

# Fixed conflict-resolution order per spec: a lower index always outranks a higher one.
PRIORITY_ORDER = ["patient_safety", "regulatory_compliance", "cost", "sustainability"]


class ExecutiveDecisionAgent(BaseAgent):
    name = str(AgentName.EXECUTIVE)
    version = "1.0.0"

    async def analyse(self, state: HealMatrixState) -> AgentResult:
        if not llm_ready():
            raise RuntimeError("No GOOGLE_API_KEY configured; executive synthesis needs the crew's LLM.")

        signals = self._collect_signals(state)
        crew_output = await self._run_crew(signals)

        return AgentResult(
            agent=self.name,
            version=self.version,
            output=crew_output,
            rationale=crew_output.get("executive_summary", "Executive synthesis completed."),
            confidence=0.75,
            messages=[],
            used_fallback=False,
            status="success",
            llm_model=settings.gemini_model,
        )

    def fallback(self, state: HealMatrixState) -> AgentResult:
        signals = self._collect_signals(state)
        action_plan, risk_register, conflicts_resolved = self._deterministic_synthesis(signals)

        summary_parts = []
        if signals["critical_stockouts"]:
            summary_parts.append(f"{len(signals['critical_stockouts'])} critical medicine stockout(s)")
        if signals["icu_overflow"]:
            summary_parts.append("ICU capacity at overflow risk")
        if signals["outbreak_warnings"]:
            summary_parts.append("an active outbreak signal")
        if signals["sustainability_grade"] and signals["sustainability_grade"] in ("D", "E"):
            summary_parts.append(f"sustainability grade {signals['sustainability_grade']}")

        executive_summary = (
            ("This cycle's priority issues: " + "; ".join(summary_parts) + ".")
            if summary_parts
            else "No critical issues this cycle; operations within normal parameters."
        )

        return AgentResult(
            agent=self.name,
            version=self.version,
            output={
                "executive_summary": executive_summary,
                "action_plan": action_plan,
                "risk_register": risk_register,
                "sustainability_recommendations": signals["reduction_opportunities"][:3],
                "conflicts_resolved": conflicts_resolved,
            },
            rationale=(
                executive_summary
                + " Generated by rule-based ranking (patient safety > regulatory compliance > "
                "cost > sustainability), not the CrewAI synthesis — no LLM configured this run."
            ),
            confidence=0.5,
            messages=[],
            used_fallback=True,
            status="success",
        )

    # ---------------------------------------------------------------- signals
    @staticmethod
    def _collect_signals(state: HealMatrixState) -> dict[str, Any]:
        """Pulls every other agent's output already in shared state into one flat
        dict — both the crew prompt and the deterministic fallback read from this,
        so the two paths can never disagree about what happened this cycle."""
        disease = result_of(state, str(AgentName.DISEASE_FORECAST)) or {}
        medicine = result_of(state, str(AgentName.MEDICINE)) or {}
        energy = result_of(state, str(AgentName.ENERGY)) or {}
        water = result_of(state, str(AgentName.WATER)) or {}
        waste = result_of(state, str(AgentName.WASTE)) or {}
        carbon = result_of(state, str(AgentName.CARBON)) or {}

        capacity_messages = messages_for(state, str(AgentName.EXECUTIVE))
        low_stock_alerts = medicine.get("output", {}).get("low_stock_alerts", [])
        critical_stockouts = [row["sku"] for row in low_stock_alerts if row.get("is_critical")]

        return {
            "outbreak_warnings": disease.get("output", {}).get("outbreak_warnings", []),
            "critical_stockouts": critical_stockouts,
            "icu_overflow": any(
                m.get("payload", {}).get("escalation") == "icu_overflow_risk" for m in capacity_messages
            ),
            "energy_savings_kwh": energy.get("output", {}).get("projected_savings_kwh", 0),
            "leak_signals": water.get("output", {}).get("leak_signals", []),
            "waste_anomalies": waste.get("output", {}).get("segregation_anomalies", []),
            "sustainability_grade": carbon.get("output", {}).get("sustainability_score", {}).get("grade"),
            "reduction_opportunities": carbon.get("output", {}).get("reduction_opportunities", []),
            "capacity_messages": capacity_messages,
        }

    @staticmethod
    def _deterministic_synthesis(signals: dict[str, Any]) -> tuple[list[dict], list[dict], list[dict]]:
        action_plan: list[dict] = []
        risk_register: list[dict] = []

        if signals["critical_stockouts"]:
            action_plan.append(
                {
                    "action": f"Expedite procurement/transfer for critical SKUs: {signals['critical_stockouts']}",
                    "owner_role": "pharmacist",
                    "horizon": "immediate",
                    "source_agent": str(AgentName.MEDICINE),
                    "impact": "patient_safety",
                }
            )
            risk_register.append({"risk": "Critical medicine stockout", "severity": "high", "category": "patient_safety"})

        if signals["icu_overflow"]:
            action_plan.append(
                {
                    "action": "Activate ICU overflow protocol; review elective admissions",
                    "owner_role": "manager",
                    "horizon": "immediate",
                    "source_agent": str(AgentName.BED_ALLOCATION),
                    "impact": "patient_safety",
                }
            )
            risk_register.append({"risk": "ICU at/above 90% occupancy", "severity": "high", "category": "patient_safety"})

        if signals["outbreak_warnings"]:
            action_plan.append(
                {
                    "action": "Pre-allocate surge capacity per Disease Forecast Agent recommendation",
                    "owner_role": "manager",
                    "horizon": "this_week",
                    "source_agent": str(AgentName.DISEASE_FORECAST),
                    "impact": "patient_safety",
                }
            )
            risk_register.append({"risk": "Outbreak signal in 14-day forecast", "severity": "medium", "category": "patient_safety"})

        for leak in signals["leak_signals"]:
            if leak.get("critical"):
                risk_register.append({"risk": "Critical water leak signal", "severity": "high", "category": "regulatory_compliance"})

        if signals["waste_anomalies"]:
            risk_register.append(
                {"risk": f"{len(signals['waste_anomalies'])} segregation anomaly(ies) flagged", "severity": "medium", "category": "regulatory_compliance"}
            )

        for lever in signals["reduction_opportunities"][:2]:
            action_plan.append(
                {
                    "action": lever.get("description", lever.get("lever", "")),
                    "owner_role": "sustainability_officer",
                    "horizon": "this_quarter",
                    "source_agent": str(AgentName.CARBON),
                    "impact": "sustainability",
                }
            )

        # Conflict example named in the spec: energy wants to cut ICU HVAC load
        # while bed allocation needs ICU overflow capacity open — patient safety wins.
        conflicts_resolved: list[dict] = []
        if signals["icu_overflow"] and signals["energy_savings_kwh"]:
            conflicts_resolved.append(
                {
                    "conflict": "Energy optimisation vs ICU overflow capacity",
                    "resolution": "Patient safety (ICU availability) takes precedence over HVAC energy savings this cycle.",
                    "priority_order": PRIORITY_ORDER,
                }
            )

        action_plan.sort(key=lambda item: PRIORITY_ORDER.index(item["impact"]) if item["impact"] in PRIORITY_ORDER else 99)
        return action_plan, risk_register, conflicts_resolved

    # -------------------------------------------------------------- crew path
    async def _run_crew(self, signals: dict[str, Any]) -> dict[str, Any]:
        """Real CrewAI synthesis. Imported lazily — crewai is a requirements-ai.txt
        dependency, not core."""
        from crewai import Agent, Crew, Process, Task

        if settings.google_api_key:
            os.environ.setdefault("GEMINI_API_KEY", settings.google_api_key)
        llm = f"gemini/{settings.gemini_model}"

        operations_analyst = Agent(
            role="Operations Analyst",
            goal="Extract the operational picture from all agent outputs this cycle.",
            backstory="You track bed capacity, patient flow and medicine supply across the hospital network.",
            llm=llm,
            verbose=False,
        )
        sustainability_auditor = Agent(
            role="Sustainability Auditor",
            goal="Assess environmental consequence and regulatory exposure from the sustainability agents' output.",
            backstory="You audit energy, water, waste and carbon figures against CPCB and internal targets.",
            llm=llm,
            verbose=False,
        )
        risk_officer = Agent(
            role="Risk Officer",
            goal="Surface patient-safety and continuity risks from every signal this cycle.",
            backstory="You flag anything that could harm a patient or interrupt care continuity.",
            llm=llm,
            verbose=False,
        )
        chief_of_staff = Agent(
            role="Chief of Staff",
            goal=(
                "Produce the final ranked action plan, resolving conflicts in the order: "
                "patient safety, then regulatory compliance, then cost, then sustainability."
            ),
            backstory="You synthesise the other three roles into one executive decision brief.",
            llm=llm,
            verbose=False,
        )

        context = json.dumps(signals, default=str)
        synthesis_task = Task(
            description=(
                "Given this cycle's agent signals as JSON:\n"
                f"{context}\n\n"
                "Produce a JSON object with exactly these keys: executive_summary (string), "
                "action_plan (list of {action, owner_role, horizon, source_agent, impact}), "
                "risk_register (list of {risk, severity, category}), "
                "sustainability_recommendations (list), conflicts_resolved (list of "
                "{conflict, resolution, priority_order}). Reply with ONLY the JSON object."
            ),
            expected_output="A single JSON object with the five keys listed above, nothing else.",
            agent=chief_of_staff,
        )

        crew = Crew(
            agents=[operations_analyst, sustainability_auditor, risk_officer, chief_of_staff],
            tasks=[synthesis_task],
            process=Process.sequential,
            verbose=False,
        )
        raw_result = await crew.kickoff_async()

        try:
            return json.loads(str(raw_result))
        except (json.JSONDecodeError, TypeError):
            return {
                "executive_summary": str(raw_result),
                "action_plan": [],
                "risk_register": [],
                "sustainability_recommendations": [],
                "conflicts_resolved": [],
            }
