"""Trains the Patient Triage Agent's XGBoost ESI classifier.

Run offline, from ``backend/``:
    python -m app.ml.training.train_triage_model

--------------------------------------------------------------------------------
Methodology, stated plainly because it matters for how the result should be read
--------------------------------------------------------------------------------
There is no real ESI-labelled hospital dataset available to this project — using
one would mean real patient records, which this platform is explicitly built to
never touch (see ``Patient.is_synthetic``). So this model is trained on a *weak
supervision* signal instead of ground truth:

  1. Vitals are generated by ``HospitalSimulator``, the same generator that drives
     every other synthetic figure in the platform, calibrated to published Indian
     tertiary-hospital vitals distributions per presenting category.
  2. Each row is labelled by the deterministic ESI rule engine
     (``app.services.triage_rules``) — the same logic a clinician's paper protocol
     encodes — with injected label noise that mimics documented ESI inter-rater
     disagreement (~85% exact agreement in published studies), so the model learns
     a *distribution* over ESI rather than memorising a lookup table.
  3. Red-flag rows are never perturbed. ESI 1 in the training data is exactly the
     set of true red-flag presentations, because teaching a safety-critical label
     to tolerate noise would be the wrong lesson regardless of how it affects the
     accuracy number.

This is a legitimate, standard way to bootstrap a clinical ML model before real
outcome data exists — it is explicitly a bootstrap, not a claim of clinical
validation. At inference time the red-flag rule pass still runs *first* and its
verdict cannot be overridden by this model's prediction (see
``app/agents/triage_agent.py``); the model's job is to add calibrated judgement
inside the non-red-flag range, not to replace the safety floor.
"""

from __future__ import annotations

import json
import platform
from datetime import datetime, timedelta, timezone
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import sklearn
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, f1_score
from sklearn.model_selection import train_test_split

from app.core.constants import DiseaseCategory
from app.ml.features import TRIAGE_FEATURE_COLUMNS, triage_features
from app.models.clinical import Vitals
from app.services.triage_rules import detect_red_flags, score_severity, score_to_esi
from app.simulator.generators import COMPLAINTS_BY_CATEGORY, HospitalSimulator, SimulationConfig

ARTIFACT_DIR = Path(__file__).resolve().parents[1] / "artifacts"
MODEL_PATH = ARTIFACT_DIR / "triage_esi_xgb.joblib"
METRICS_PATH = ARTIFACT_DIR / "triage_esi_metrics.json"
MODEL_VERSION = "triage_xgb@1.0.0"

N_SAMPLES = 24_000
NOISE_PROBABILITY = 0.15  # see module docstring: models ESI inter-rater disagreement
TRAINING_SEED = 20260723  # the date this pipeline was built; keeps runs reproducible

CATEGORIES = [str(category) for category in DiseaseCategory]
ESI_CLASSES = [1, 2, 3, 4, 5]


def _label_with_noise(esi_level: int, red_flags: list[str], rng: np.random.Generator) -> int:
    """Perturb the rule-engine label within the non-critical band only. See module docstring."""
    if red_flags:
        return 1
    if rng.random() >= NOISE_PROBABILITY:
        return esi_level
    shift = int(rng.choice([-1, 1]))
    return int(np.clip(esi_level + shift, 2, 5))


def build_dataset(n_samples: int = N_SAMPLES, seed: int = TRAINING_SEED) -> pd.DataFrame:
    """Synthetic, weak-labelled training rows. See module docstring for methodology."""
    simulator = HospitalSimulator(SimulationConfig(seed=seed))
    rng = np.random.default_rng(seed + 1)
    base_moment = datetime(2025, 1, 1, tzinfo=timezone.utc)

    records: list[dict] = []
    for i in range(n_samples):
        moment = base_moment + timedelta(hours=int(rng.integers(0, 365 * 24)))
        category = CATEGORIES[i % len(CATEGORIES)]

        patient = simulator.generate_patient(moment)
        vitals_dict = simulator.generate_vitals(category, patient["age"])
        vitals = Vitals(**vitals_dict)
        complaint = str(rng.choice(COMPLAINTS_BY_CATEGORY[category]))
        comorbidity_count = len(patient["comorbidities"])

        red_flags = detect_red_flags(vitals)
        score = score_severity(vitals, patient["age"], comorbidity_count)
        rule_esi = score_to_esi(score, red_flags)
        label = _label_with_noise(rule_esi, red_flags, rng)

        row = triage_features(
            vitals=vitals,
            age=patient["age"],
            sex=patient["sex"],
            comorbidity_count=comorbidity_count,
            chief_complaint=complaint,
        )
        row["esi_level"] = label
        row["disease_category"] = category
        records.append(row)

    return pd.DataFrame.from_records(records)


def train() -> dict:
    """Build the dataset, train, evaluate, and persist the artifact + metrics report."""
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

    df = build_dataset()
    X = df[TRIAGE_FEATURE_COLUMNS]
    y = df["esi_level"].map({level: idx for idx, level in enumerate(ESI_CLASSES)})

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=TRAINING_SEED, stratify=y
    )

    model = xgb.XGBClassifier(
        objective="multi:softprob",
        num_class=len(ESI_CLASSES),
        n_estimators=260,
        max_depth=5,
        learning_rate=0.08,
        subsample=0.85,
        colsample_bytree=0.85,
        eval_metric="mlogloss",
        random_state=TRAINING_SEED,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    report = classification_report(
        y_test, predictions, target_names=[f"ESI{level}" for level in ESI_CLASSES], output_dict=True
    )
    accuracy = float(accuracy_score(y_test, predictions))
    macro_f1 = float(f1_score(y_test, predictions, average="macro"))

    joblib.dump(
        {
            "model": model,
            "feature_columns": TRIAGE_FEATURE_COLUMNS,
            "esi_classes": ESI_CLASSES,
            "model_version": MODEL_VERSION,
        },
        MODEL_PATH,
    )

    metrics = {
        "model_version": MODEL_VERSION,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "n_samples": N_SAMPLES,
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "noise_probability": NOISE_PROBABILITY,
        "accuracy": round(accuracy, 4),
        "macro_f1": round(macro_f1, 4),
        "classification_report": report,
        "feature_columns": TRIAGE_FEATURE_COLUMNS,
        "library_versions": {
            "xgboost": xgb.__version__,
            "scikit_learn": sklearn.__version__,
            "python": platform.python_version(),
        },
        "methodology": (
            "Weak-supervision bootstrap: synthetic vitals from HospitalSimulator, "
            "labelled by the deterministic ESI rule engine with injected inter-rater "
            "noise on non-red-flag rows only. Not trained on real patient outcomes. "
            "See the module docstring in train_triage_model.py for the full rationale."
        ),
    }
    METRICS_PATH.write_text(json.dumps(metrics, indent=2))

    return metrics


if __name__ == "__main__":
    result = train()
    print(f"Trained {result['model_version']}")
    print(f"  accuracy   = {result['accuracy']}")
    print(f"  macro F1   = {result['macro_f1']}")
    print(f"  artifact   -> {MODEL_PATH}")
    print(f"  metrics    -> {METRICS_PATH}")
