"""Trains the Disease Forecast Agent's XGBoost 14-day admissions forecaster.

Run offline, from ``backend/``:
    python -m app.ml.training.train_admissions_forecast

--------------------------------------------------------------------------------
Methodology
--------------------------------------------------------------------------------
Daily total-arrival counts are generated by ``HospitalSimulator.arrivals_for_hour``
summed to a daily total — the same non-homogeneous-Poisson model (hour-of-day
profile x weekday multiplier x seasonal disease mix) that drives every other
"admissions" figure in the demo, run across several independent seeds so the
regressor sees more than one realised trajectory of the same underlying process.

The model is trained as a *single-step* regressor: given a trailing 14-day window
plus calendar features, predict tomorrow's count. The 14-day forecast the agent
actually needs is produced by feeding the model's own prediction back into the
window and rolling forward (see ``predict_admissions_14d`` in
``app/ml/inference.py``) — this is why the evaluation below reports both one-step
error and true recursive 14-day-ahead error: the latter is what the accuracy
number should mean when read by anyone but a machine-learning specialist.
"""

from __future__ import annotations

import json
import platform
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import joblib
import numpy as np
import sklearn
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error

from app.simulator.generators import HospitalSimulator, SimulationConfig, hours_between

ARTIFACT_DIR = Path(__file__).resolve().parents[1] / "artifacts"
MODEL_PATH = ARTIFACT_DIR / "admissions_forecast_xgb.joblib"
METRICS_PATH = ARTIFACT_DIR / "admissions_forecast_metrics.json"
MODEL_VERSION = "admissions_forecast_xgb@1.0.0"

ADMISSIONS_LAG_DAYS = 14
FORECAST_HORIZON_DAYS = 14
TRAINING_SEEDS = [20260723, 20260724, 20260725, 20260726]
DAYS_PER_SERIES = 1095  # 3 synthetic years per seed

FEATURE_COLUMNS: list[str] = [
    *[f"lag_{i}" for i in range(1, ADMISSIONS_LAG_DAYS + 1)],
    "rolling_mean_7",
    "rolling_mean_14",
    "weekday_sin",
    "weekday_cos",
    "month_sin",
    "month_cos",
]


def build_feature_row(window: list[float], target_weekday: int, target_month: int) -> dict[str, float]:
    """Feature dict for predicting the day *after* ``window`` (oldest first, newest last).

    ``target_weekday`` (0=Monday) and ``target_month`` (1-12) describe the day being
    predicted, not the window — a Monday surge looks different from a Friday one even
    given an identical trailing history.
    """
    if len(window) != ADMISSIONS_LAG_DAYS:
        raise ValueError(f"window must have exactly {ADMISSIONS_LAG_DAYS} days, got {len(window)}")

    features: dict[str, float] = {}
    for i in range(1, ADMISSIONS_LAG_DAYS + 1):
        features[f"lag_{i}"] = float(window[-i])
    features["rolling_mean_7"] = float(np.mean(window[-7:]))
    features["rolling_mean_14"] = float(np.mean(window))
    features["weekday_sin"] = float(np.sin(2 * np.pi * target_weekday / 7))
    features["weekday_cos"] = float(np.cos(2 * np.pi * target_weekday / 7))
    features["month_sin"] = float(np.sin(2 * np.pi * target_month / 12))
    features["month_cos"] = float(np.cos(2 * np.pi * target_month / 12))
    return features


def _daily_series(seed: int, n_days: int) -> list[float]:
    """One seeded hospital's daily arrival-count trajectory, starting 2023-01-01."""
    simulator = HospitalSimulator(SimulationConfig(seed=seed))
    start = datetime(2023, 1, 1, tzinfo=timezone.utc)
    end = start + timedelta(days=n_days - 1, hours=23)

    hourly_counts = [simulator.arrivals_for_hour(moment) for moment in hours_between(start, end)]
    # Fold 24 hourly counts into each day's total.
    return [
        float(sum(hourly_counts[day * 24 : (day + 1) * 24]))
        for day in range(n_days)
    ]


def _rows_for_series(series: list[float], series_start: date) -> tuple[list[dict], list[float]]:
    rows: list[dict] = []
    targets: list[float] = []
    for i in range(ADMISSIONS_LAG_DAYS, len(series)):
        target_day = series_start + timedelta(days=i)
        window = series[i - ADMISSIONS_LAG_DAYS : i]
        rows.append(build_feature_row(window, target_day.weekday(), target_day.month))
        targets.append(series[i])
    return rows, targets


def build_dataset() -> tuple[np.ndarray, np.ndarray, list[float], date]:
    """Concatenate rows from every training seed's series. Returns X, y, plus one
    held-back series (the last seed) for the recursive-forecast evaluation."""
    all_rows: list[dict] = []
    all_targets: list[float] = []

    for seed in TRAINING_SEEDS:
        series = _daily_series(seed, DAYS_PER_SERIES)
        rows, targets = _rows_for_series(series, date(2023, 1, 1))
        all_rows.extend(rows)
        all_targets.extend(targets)

    X = np.array([[row[col] for col in FEATURE_COLUMNS] for row in all_rows])
    y = np.array(all_targets)
    return X, y, all_rows, date(2023, 1, 1)


def _recursive_forecast_error(model: xgb.XGBRegressor, seed: int) -> dict[str, float]:
    """True 14-day-ahead recursive rollout accuracy on an unseen seeded series.

    Picks several anchor points in a held-out trajectory, rolls the model forward
    ``FORECAST_HORIZON_DAYS`` days feeding its own predictions back in (exactly what
    ``predict_admissions_14d`` does at inference time), and compares against the
    simulator's actual values for those same future days.
    """
    series = _daily_series(seed, DAYS_PER_SERIES)
    series_start = date(2023, 1, 1)

    anchors = range(400, DAYS_PER_SERIES - FORECAST_HORIZON_DAYS - 1, 60)
    absolute_errors: list[float] = []

    for anchor in anchors:
        window = list(series[anchor - ADMISSIONS_LAG_DAYS : anchor])
        actual_future = series[anchor : anchor + FORECAST_HORIZON_DAYS]

        rolling_window = window
        for step in range(FORECAST_HORIZON_DAYS):
            target_day = series_start + timedelta(days=anchor + step)
            features = build_feature_row(rolling_window, target_day.weekday(), target_day.month)
            row = np.array([[features[col] for col in FEATURE_COLUMNS]])
            predicted = max(float(model.predict(row)[0]), 0.0)
            absolute_errors.append(abs(predicted - actual_future[step]))
            rolling_window = rolling_window[1:] + [predicted]

    return {
        "mae_14d_recursive": round(float(np.mean(absolute_errors)), 2),
        "n_forecasts_evaluated": len(list(anchors)) * FORECAST_HORIZON_DAYS,
    }


def train() -> dict:
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

    X, y, _, _ = build_dataset()

    # Chronological split, not random shuffling — adjacent days share lag features,
    # so a random split would leak the test day's neighbours into training.
    split = int(len(X) * 0.8)
    X_train, X_test = X[:split], X[split:]
    y_train, y_test = y[:split], y[split:]

    model = xgb.XGBRegressor(
        n_estimators=320,
        max_depth=5,
        learning_rate=0.06,
        subsample=0.85,
        colsample_bytree=0.85,
        random_state=20260723,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    one_step_mae = float(mean_absolute_error(y_test, predictions))
    one_step_rmse = float(np.sqrt(mean_squared_error(y_test, predictions)))
    mean_actual = float(np.mean(y_test))

    # Evaluated on an unseen seed entirely (not one of the training seeds).
    recursive_metrics = _recursive_forecast_error(model, seed=990001)

    joblib.dump(
        {
            "model": model,
            "feature_columns": FEATURE_COLUMNS,
            "lag_days": ADMISSIONS_LAG_DAYS,
            "model_version": MODEL_VERSION,
        },
        MODEL_PATH,
    )

    metrics = {
        "model_version": MODEL_VERSION,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "n_samples": int(len(X)),
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "training_seeds": TRAINING_SEEDS,
        "one_step_mae": round(one_step_mae, 2),
        "one_step_rmse": round(one_step_rmse, 2),
        "mean_actual_daily_arrivals": round(mean_actual, 2),
        "one_step_mape_pct": round(one_step_mae / mean_actual * 100, 2),
        **recursive_metrics,
        "feature_columns": FEATURE_COLUMNS,
        "library_versions": {
            "xgboost": xgb.__version__,
            "scikit_learn": sklearn.__version__,
            "python": platform.python_version(),
        },
        "methodology": (
            "Trained on daily arrival counts from HospitalSimulator across 4 seeded "
            "3-year trajectories (non-homogeneous Poisson: hour-of-day x weekday x "
            "seasonal disease mix). Evaluated both as a one-step regressor (chronological "
            "80/20 split) and as the true 14-day recursive rollout the agent actually runs, "
            "on a fifth, entirely unseen seed. See train_admissions_forecast.py docstring."
        ),
    }
    METRICS_PATH.write_text(json.dumps(metrics, indent=2))
    return metrics


if __name__ == "__main__":
    result = train()
    print(f"Trained {result['model_version']}")
    print(f"  one-step MAE      = {result['one_step_mae']} (MAPE {result['one_step_mape_pct']}%)")
    print(f"  14d recursive MAE = {result['mae_14d_recursive']}")
    print(f"  artifact          -> {MODEL_PATH}")
    print(f"  metrics           -> {METRICS_PATH}")
